OnnxModel: onnx/resnet50.onnx
#InputData: keras/KERAS_3layer_input_features.dat
#OutputPredictions: keras/KERAS_3layer_predictions.dat
OutputDir: my-hls-test-onnx-v2
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5

IOType: io_serial # options: io_serial/io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<8,0>
    ReuseFactor: 1048576
  LayerType:
    Dense:
      ReuseFactor: 1048576
      Strategy: Latency
      Compression: True
    Conv2D:
      ReuseFactor: 1048576
      Strategy: Latency
      Compression: True
