OnnxModel: resnet50/model.onnx
OutputDir: resnet50-hls
ProjectName: myproject
XilinxPart: xcku115-flvb2104-2-i
ClockPeriod: 5
Backend: Vivado
IOType: io_parallel
HLSConfig:
  Model:
    Precision: ap_fixed<16,6>
    ReuseFactor: 128
    Strategy: Resource
  LayerName:
    Conv1:
      ReuseFactor: 112
    Conv8:
      ReuseFactor: 144
    Conv20:
      ReuseFactor: 144
    Conv30:
      ReuseFactor: 144